/*
Navicat MySQL Data Transfer

Source Server         : ll
Source Server Version : 50722
Source Host           : localhost:3306
Source Database       : qa

Target Server Type    : MYSQL
Target Server Version : 50722
File Encoding         : 65001

Date: 2020-05-24 13:48:38
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for comment
-- ----------------------------
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content` text NOT NULL,
  `user_id` int(11) NOT NULL,
  `entity_id` int(11) NOT NULL,
  `entity_type` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `entity_index` (`entity_id`,`entity_type`)
) ENGINE=InnoDB AUTO_INCREMENT=193 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of comment
-- ----------------------------
INSERT INTO `comment` VALUES ('1', 'Like most things in life, \"knowing how to swim\" is not a black and white thing. You don\'t go straight from \"has never been in a body of water larger than a puddle\" to \"Michael Phelps\", with nothing in between.', '1', '2', '1', '2019-10-22 19:48:00', '0');
INSERT INTO `comment` VALUES ('2', 'I\'d be surprised if the tub, no matter how long and wide it is, were so deep that he couldn\'t stand in it with his head above the water.', '5', '2', '1', '2019-10-22 20:27:28', '0');
INSERT INTO `comment` VALUES ('3', 'I’m also guessing that the Dursleys would go to the pool with Dudley amd Harry, get Dudley lessons, and let Harry try to drown.', '1', '4', '1', '2019-10-22 20:30:38', '0');
INSERT INTO `comment` VALUES ('4', 'I\'ve known how to swim since I was 2 and have no problem going into any kind of water. What I don\'t know how to do (or at least, I haven\'t done it much and am not good at it at all) is dive down deep and stay there. The human body is very bouyant. Swimming deep is a skill that takes practice to develop.', '1', '4', '1', '2019-10-22 20:30:44', '0');
INSERT INTO `comment` VALUES ('5', 'His time in primary school was entirely before they were required to provide swimming lessons (that was 1994), but I agree that he likely did have lessons, given that he can swim to some degree.', '2', '4', '1', '2019-10-22 20:32:42', '0');
INSERT INTO `comment` VALUES ('6', 'Perhaps it\'s a British-ism, but I\'m not sure what you mean by \'casual\' with regard to drowning.', '2', '5', '1', '2019-10-23 10:00:06', '0');
INSERT INTO `comment` VALUES ('7', '@TylerH - \'casual\' drowning would be drowning that\'s easily avoided by even a tiny amount of exposure to swimming, such as in a placid lake or a swimming pool without a lifeguard. It means \"You can swim well enough that you aren\'t at risk of drowning in otherwise calm water.', '7', '5', '1', '2019-10-23 10:00:06', '0');
INSERT INTO `comment` VALUES ('8', '@TylerH in the UK we still have formal drownings where young women are taken to lakes, ponds and streams to be formally tested. No amount of lessons can save you from that unless you weigh the same as a duck. (/s)', '3', '5', '1', '2019-10-23 10:00:06', '0');
INSERT INTO `comment` VALUES ('9', '@MD-Tech Or have a natural gift for knots and plenty of practise at holding your breath underwater. (Miss Tick from Terry Pratchett\'s \"Tiffany Aching\" strand of Diskworld books.) ', '10', '5', '1', '2019-10-23 10:00:07', '0');
INSERT INTO `comment` VALUES ('10', 'You can support the post by marking it as the answer if it helped you and upvoting! Thanks ', '2', '5', '1', '2019-10-23 10:00:07', '0');
INSERT INTO `comment` VALUES ('11', 'Have you tried translating the messages on the display by the usual means (look up in a dictionary, type in an app, take a photo and ask a Hebrew speaker, etc)?', '1', '5', '1', '2019-10-23 10:00:07', '0');
INSERT INTO `comment` VALUES ('12', 'I am more curious why the OP is asking a bunch of internet strangers, 99% of whom will have never, ever, run into this issue. Instead, why not ask someone who lives in Israel and works at a service station?', '4', '5', '1', '2019-10-23 10:00:07', '0');
INSERT INTO `comment` VALUES ('13', 'Or ask one of those people who have been nice enough to help you to explain what they\'re doing so you can learn. ', '14', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('14', '@CGCampbell: OP was assuming there are Israeli locals on Travel.SX, and - s/he was right.', '16', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('15', 'The English language countries are the US, Canada, UK, New Zealand and Australia. Everyone else has a different language. So don\'t be surprised to NOT see foreign languages, just like you don\'t see Portugese or Chinese on gas pumps in the US. ', '2', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('16', 'Depending on the local software, a fake but valid ID number such as 122222227 will work better than a random ID.', '4', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('17', 'Why do they need the plate number? Is it about tracking stolen vehicles or something? (E.g. if they look up the plate and id and you\'re not the owner, the police now know where to look for you?) What if I were driving with a friend and they offered to pay for the gas? (I\'m just curious, not planning a trip to Israel any time soon.)', '5', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('18', '@DarrelHoffman this is a wild guess, but I know many years ago Israel had a gas rationing system where cars (based on license plate) were only allowed to drive on alternating days. Maybe some kind of holdover from that era?', '14', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('19', 'Some people have gas cards that are only supposed to be used with a specific car. Typing in the correct license plate is a (minor) hurdle to prevent you from borrowing a friend\'s card. (The gas purchased using such a card is usually subsidized by an employer.)', '12', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('20', 'I think the license plate number is part of credit card fraud detection heuristics - an irregularity doesn\'t mean there\'s a problem, just that extra attention marry be needed. In a couple of cases I typed it wrong the transaction was approved.', '14', '5', '1', '2019-10-23 10:00:08', '0');
INSERT INTO `comment` VALUES ('21', 'Why do they ask for license plate number? What if you enter the wrong one?', '8', '5', '1', '2019-10-23 10:00:09', '0');
INSERT INTO `comment` VALUES ('22', 'At best, in order to print it on the receipt. At worst, as a spying measure. \"What if you enter the wrong one\" <- nothing. You can safely enter some other valid license plate number (not sure what\'s the verification rule). ', '11', '6', '1', '2019-10-23 10:00:12', '0');
INSERT INTO `comment` VALUES ('23', 'Can we even demand $det(A)=det(B)=det(C)=1$?', '4', '6', '1', '2019-10-23 10:00:12', '0');
INSERT INTO `comment` VALUES ('24', 'Hmm, it may still be true with that assumption. However notice that the example here and in Robert’s answer do not work in that case.', '4', '7', '1', '2019-10-23 10:00:15', '0');
INSERT INTO `comment` VALUES ('25', 'Of possible interest, Niven, Ivan. Fermat’s theorem for matrices. Duke Math. J. 15 (1948), no. 3, 823--826. doi:10.1215/S0012-7094-48-01574-9. projecteuclid.org/euclid.dmj/1077475036, Mathematical Reviews number (MathSciNet) MR0026672, Zentralblatt MATH identifier 0032.00102', '14', '7', '1', '2019-10-23 10:00:15', '0');
INSERT INTO `comment` VALUES ('26', 'There\'s also Schwarz, Štefan, Fermat\'s theorem for matrices revisited. (English). Mathematica Slovaca, vol. 35 (1985), issue 4, pp. 343-347 MSC: 11C20, 15A33, 20M10 | MR 820630 | Zbl 0584.15007 at dml.cz/handle/10338.dmlcz/136402 ', '2', '7', '1', '2019-10-23 10:00:15', '0');
INSERT INTO `comment` VALUES ('27', 'It is about a different Fermat theorem. ', '12', '8', '1', '2019-10-23 10:00:18', '0');
INSERT INTO `comment` VALUES ('28', 'Hey, this is an excellent answer, so instead of supplying another answer, I wanted to add one more common problem and solution to yours: No Vents Cut in Top. Per Cook\'s Illustrated, unless you cut vents in the top of the calzone, it will trap steam -- even with relatively dry ingredients. You kind of mention this in the Greasy Crust problem, but it would be better to call it out as a separate issue.', '10', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('29', ' i\'ve added your suggestion to the crust part. I must confess, for some reason i find myself opposed to slits, it\'s almost cheating, but I do appreciate how they can produce a better result with less prep and effort.', '5', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('30', 'I feel like that\'s worth putting as a separate answer, as it\'s really a different thing - dandavis is explaining how to adjust the recipe, while you are explaining a different way to solve it. Great answer here, too! ', '7', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('31', 'I would add the difference between static and dynamic/kinetic/sliding friction. You change your center of mass by moving slowly, such that static friction keeps the chair in place. Then you move quickly in the other direction such that static friction is overcome and the chair moves backwards underneath you (subject to the weaker dynamic friction), similarly to your frictionless case.', '1', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('32', 'I quite like this one, where I can set up a log file at the top of a script and write to it throughout without needing either a global variable or to remember to change all occurrences of a filename:', '7', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('33', 'Here are few other ways to append text to a file.', '1', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('34', 'Using a here-document approach:', '1', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('35', 'Why downvote? This is a valid answer tho.', '5', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('36', 'See updated answer with tests', '13', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('37', 'Using the Unix file editors. Both GNU and BSD version.\r\nUsing ed(1) with printf', '11', '8', '1', '2019-10-23 10:00:19', '0');
INSERT INTO `comment` VALUES ('38', 'This is creative, but can you use a line of string instead of an input file? ', '8', '9', '1', '2019-10-23 10:00:25', '0');
INSERT INTO `comment` VALUES ('39', 'yes certainly, dd conv=notruct oflag=append of=destination <<<\'Some string of text\'', '7', '9', '1', '2019-10-23 10:00:25', '0');
INSERT INTO `comment` VALUES ('40', 'my version of dd doesn\'t understand conv=append; it has to be an oflag. Are you sure your answer actually works? ', '1', '9', '1', '2019-10-23 10:00:25', '0');
INSERT INTO `comment` VALUES ('41', 'The sequence you gave does not work with either vim nor vi please test that before posting.', '12', '9', '1', '2019-10-23 10:00:26', '0');
INSERT INTO `comment` VALUES ('42', 'In vi and its clones, Gi will insert at the beginning of the last line. Perhaps you intended GA or Go?', '9', '9', '1', '2019-10-23 10:00:26', '0');
INSERT INTO `comment` VALUES ('43', 'Ctrl G? Surely you mean Shift G', '15', '9', '1', '2019-10-23 10:00:26', '0');
INSERT INTO `comment` VALUES ('44', 'Or another variant:\r\nDateListPlot[ReplacePart[#, 1 -> Prepend[#[[1]], 2020]] & /@ data]', '16', '9', '1', '2019-10-23 10:00:26', '0');
INSERT INTO `comment` VALUES ('45', 'As to the ok-ness or not, I\'d wager that it\'s more an aggression (and possibly a show-off) than a wish to be helpful. So it should be discouraged, yes. But privately, not publicly.', '10', '9', '1', '2019-10-23 10:00:26', '0');
INSERT INTO `comment` VALUES ('46', 'Just to add some context. This happened to me (as the student). I was naive and it pained me to hear silence for a few seconds if the other student didn\'t know the answer. My lecturer took me into a side-room after class quietly and explained how it wasn\'t helping the class and he appreciated that I was aware, but to let the other students answer the questions. He advised that I don\'t answer any questions in the class, which actually changed my attitude for classes ever since that talk and I always took a back seat unless I was stuck/unsure. ', '10', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('47', 'If a question gets answered that\'s good. Even more so by an engaged student. What would be your lesson to the student to stop answering questions? Respecting your authority? If that\'s the only reason for you to call him into a meeting, you should rethink your motives. Authority has to serve a purpose. ', '11', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('48', 'Following from @image, students can give better answers than professors, because they better understand their peers\' knowledge.', '8', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('49', 'The way I understood the question, the professor wants to explain the context and required knowledge, so the student and his silent compatriots know, why the answer is correct. And the interrupting student only seems to be shouting out the factual answer, without explaining any underlying goings-on. Aside from the interruption of class and possible interpretation of the other students, this leaves a lot of learning on the table.', '2', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('50', 'This student\'s answers are generally correct. She comes across as very arrogant. Though. she is retaking my class because she got very low score last time. I overheard that she had studied this material from a teacher from School X (a top school) and it was way better than what\'s been done in this class.', '7', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('51', 'Arrogance is painful, of course and reflects badly on her, I expect. I might lean, in such a case, as requiring a \"hand up\" first with explicit permission to speak. ', '15', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('52', 'One thing that such a student fails to understand, of course, is that often the best answer is a minimal answer. An answer that lets students develop insight, not just get answers. Saying too much in answering a student question may be worse than saying nothing. ', '3', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('53', 'Buffy, I like your approach. A premature answer also robs me of the need to explore the question. Who else doesn\'t know? Why, are they missing context? Other audience members are less likely to admit to not knowing if the answer has already been given.', '14', '9', '1', '2019-10-23 10:00:27', '0');
INSERT INTO `comment` VALUES ('54', 'That seems suspicious, so they have so little confidence in your teaching that they were able to take material from a class they weren\'t even taking at a completely different university and understand the material way better? If so It is not in the students best interest to not answer these questions because clearly they are gaining experience and study in what ever subject you are teaching, even if you feel it is best for the class. I thought it was just an overeager student, but given this new information I\'m afraid you may have inadvertently caused this. ', '1', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('55', 'I\'ve found that \"do you understand...?\" is almost always answered with a yes, even when it\'s not the case. I don\'t have a good replacement question. The closest I\'ve come is, \"Is there anything I should explain in more detail?\" That, at least, turns \"you\" into \"I\" and sometimes elicits a further question.', '14', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('56', 'As a student I always very much disliked having my questions answered by the class know-it-all rather than the professor. I could have an enjoyable interactive session (it wouldn\'t be a lecture) at the local coffee shop. I\'m paying tuition to hear material from a real professor. ', '14', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('57', 'You pay tuition to learn the promised material, as the tutors see fit. Other than that, your own motivation of paying money does not matter, unfortunately. ', '15', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('58', 'Regarding #2, I think you\'re better off giving a polite directive rather than making a request, which is how your \"I need you to not jump in...\" reads to me anyway. Maybe change \"make your request\" to \"give your directive\" (or some synonym of \"directive\"). I think emphasizing courtesy and explaining yourself is good, while still gently asserting your authority as prof. If it really is phrased as a request, then authority isn\'t being asserted properly which could backfire. Assertion of authority should be polite and show appreciation for the student, and be constructive, but it is needed. ', '10', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('59', ' I\'d say \"I need you to do X\" from an authority figure is a polite directive (imagine hearing it from your boss), but that will depend on cultural context.', '10', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('60', 'I agree. I\'m just thinking someone could misinterpret \"make your request\" as something other than giving a polite directive, so that\'s the part I was suggesting to change; I think the actual wording you suggest could work well for the situation. ', '8', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('61', 'Let him/her keep answering IF the student consistently gets the answers right. It helps the student learn and spurs class participation. Learning happens best when it is a two-way street.', '14', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('62', 'I remember a situation where this happened in class. The teacher put down the interrupting student in class for everyone, rather angrily. He told the student something along the lines of \"Sure, you might pass the class without problems, but that doesn\'t mean everyone here will\".', '5', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('63', 'Can you clarify what NVC is?', '8', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('64', 'It stands for \'nonviolent communication\'. To pluck a definition from the internet: \"A way of thinking, speaking and acting that contributes to mutual connection and cooperation.\" I am not an expert in any sense, but it is basically a set of techniques that can help you communicate about conflicts (among things) in a way so that relations between two parties is strengthened instead of weakened.', '14', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('65', 'Recruit them as extraofficial help. Task them with answering questions in the online fora (official or non-official). Talk to them and work out some etiquette on answering questions in class: give others time to think the problem through, let others answer first, in general, be polite to co-students.', '7', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('66', 'I suspect that would be discriminatory if they had a learning disability, such as ADHD or Aspergers etc. It also doesn\'t seem like a \"golden rule\" approach. ', '5', '9', '1', '2019-10-23 10:00:28', '0');
INSERT INTO `comment` VALUES ('67', 'Just put down the interrupter. Well thanks Hermione. Boy somebody likes to jump in an answer. Well now, not everyone is taking the class for the third time. Stuff like that.', '4', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('68', 'IMO this may (probably) come off as arrogant and things such as not everyone is taking the class for the third time are disrespectful to the student even if he or she is annoying. I\'m not sure this will help OP resolving this simple problem. ', '12', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('69', 'Are you the user Guest? If so, I normally enjoy your answers (they are often better than most of this site\'s regulars) but this answer is just horror. ', '7', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('70', 'Most male British royals take parts in whatever conflicts Britain participates. I think the current young princes (potential heirs) served in Afganistan for some time. ', '9', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('71', 'True. However immediate heirs are rarely sent to combat. Wills was not in combat, and Harry probably isn\'t going to be king. George VI was probably only allowed to fight because he wasn\'t supposed to be king either.', '16', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('72', 'Thank you for the answer. I should have been clearer: I meant while reigning. That said, presumably George VI actually fired a gun, from the sound of this? ', '7', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('73', 'A turret officer would have been in command of one of the main guns of a battleship. So he would have been next to the gun and given the command to fire, though probably not actually pulled the \"trigger\" himself. That\'s definitely \"in combat\" from a navy point of view, and he is running exactly the same risks as any Ordinary Seaman.', '9', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('74', 'Good enough for me... although the main issue is still that he wasn’t reigning at this time.', '16', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('75', 'Now close? Napoleon would have had to be within 400 yards I expect to be hit by musket fire, even spent.', '6', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('76', 'Thanks for the answer. I would say this \"kind of counts\". Napoleon certainly wasn\'t a king, though he was an emperor (albeit not one of noble descent). Evidently he didn\'t make use of a weapon himself whilst Emperor of the French, though the fact he was wounded counts for something.', '6', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('77', ' My pleasure. However, I believe your \"distinction\" between kings and emperors is misplaced. (1) To be meaningful, I believe you should be looking for sovereigns rather than monarchs. Those are the family lines held to be \"acceptable for royal marriage\" and would include the many houses of \"Imperial Princes\" in the H.R.E. (2) The proper title of the Hapsburg Emperors was King of the Romans, and for many centuries they were also King of Bohemia as a personal possession in addition to Carpathia.', '6', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('78', 'Well, I sort of am. It\'s a fair point. The only reason I slightly hesitated with Napoleon (and I write \"slightly\") is that he was not from a (noble) dynasty/house... although it could be said he formed a short-lived one of his own. Like you say, the Holy Roman Emperors with \"Kings of the Romans\" (and earlier on, \"King of Italy\" or \"Rex Italiae\", though I guess that was dropped by the time of the first Habsburg, since they had no control over Italy whatsoever). ', '2', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('79', 'The last in the world it was Abdulla, Khalifa of Sudan that was killed at Umm Diwaykara in 1899. Definitely, that was the most personal participation.\r\nAnd Khalifa > Sultan = Emperor, so in the feudal sense, he was higher than any king.', '7', '9', '1', '2019-10-23 10:00:29', '0');
INSERT INTO `comment` VALUES ('80', 'Thanks for the answer. Definitely not European though! ', '20', '5', '1', '2019-10-24 16:10:40', '0');
INSERT INTO `comment` VALUES ('81', 'Hmm, it may still be true with that assumption. However notice that the example here and in Robert’s answer do not work in that case.', '5', '11', '1', '2019-10-27 10:00:07', '0');
INSERT INTO `comment` VALUES ('82', 'Of possible interest, Niven, Ivan. Fermat’s theorem for matrices. Duke Math. J. 15 (1948), no. 3, 823--826. doi:10.1215/S0012-7094-48-01574-9. projecteuclid.org/euclid.dmj/1077475036, Mathematical Reviews number (MathSciNet) MR0026672, Zentralblatt MATH identifier 0032.00102', '7', '11', '1', '2019-10-27 10:00:07', '0');
INSERT INTO `comment` VALUES ('83', 'There\'s also Schwarz, Štefan, Fermat\'s theorem for matrices revisited. (English). Mathematica Slovaca, vol. 35 (1985), issue 4, pp. 343-347 MSC: 11C20, 15A33, 20M10 | MR 820630 | Zbl 0584.15007 at dml.cz/handle/10338.dmlcz/136402 ', '5', '11', '1', '2019-10-27 10:00:07', '0');
INSERT INTO `comment` VALUES ('84', ' It is about a different Fermat theorem.', '4', '11', '1', '2019-10-27 10:00:07', '0');
INSERT INTO `comment` VALUES ('85', ' On what sort of surface are you cooking your calzone, and on what sort of surface are you placing it after taking it out of the oven? I find that if I place a calzone on a wire rack (or a wire pizza pan) after cooking, it\'s less likely that the bottom gets wet from steam trapped underneath as it cools. ', '5', '11', '1', '2019-10-27 10:00:08', '0');
INSERT INTO `comment` VALUES ('86', 'Hey, this is an excellent answer, so instead of supplying another answer, I wanted to add one more common problem and solution to yours: No Vents Cut in Top. Per Cook\'s Illustrated, unless you cut vents in the top of the calzone, it will trap steam -- even with relatively dry ingredients. You kind of mention this in the Greasy Crust problem, but it would be better to call it out as a separate issue.', '2', '11', '1', '2019-10-27 10:00:08', '0');
INSERT INTO `comment` VALUES ('87', ' i\'ve added your suggestion to the crust part. I must confess, for some reason i find myself opposed to slits, it\'s almost cheating, but I do appreciate how they can produce a better result with less prep and effort.', '8', '11', '1', '2019-10-27 10:00:08', '0');
INSERT INTO `comment` VALUES ('88', 'I feel like that\'s worth putting as a separate answer, as it\'s really a different thing - dandavis is explaining how to adjust the recipe, while you are explaining a different way to solve it. Great answer here, too! ', '13', '12', '1', '2019-10-27 10:00:11', '0');
INSERT INTO `comment` VALUES ('89', 'Does this answer your question? Internal forces in an isolated system', '3', '12', '1', '2019-10-27 10:00:11', '0');
INSERT INTO `comment` VALUES ('90', 'I would add the difference between static and dynamic/kinetic/sliding friction. You change your center of mass by moving slowly, such that static friction keeps the chair in place. Then you move quickly in the other direction such that static friction is overcome and the chair moves backwards underneath you (subject to the weaker dynamic friction), similarly to your frictionless case. ', '1', '12', '1', '2019-10-27 10:00:11', '0');
INSERT INTO `comment` VALUES ('91', 'Note that you can group commands together (a ; b ; c) >> file', '14', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('92', 'Why downvote? This is a valid answer tho.', '15', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('93', 'See updated answer with tests.', '4', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('94', 'This is very, very useful in scripts. ', '11', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('95', 'This is creative, but can you use a line of string instead of an input file?', '9', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('96', 'yes certainly, dd conv=notruct oflag=append of=destination <<<\'Some string of text\'', '8', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('97', 'Paul_Pedant my version of dd doesn\'t understand conv=append; it has to be an oflag. Are you sure your answer actually works? ', '13', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('98', 'Note that you can group commands together (a ; b ; c) >> file', '9', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('99', 'Using the Unix file editors. Both GNU and BSD version.\r\n\r\nUsing ed(1) with printf\r\n\r\nprintf \'%s\n\' \'$a\' \'foo bar baz\' . w | ed -s file.txt\r\nThe bash specific but more cryptic syntax using the $\' \' shell quoting and a herestring\r\n\r\ned -s file.txt <<< $\'$a\nfoo bar baz\n.\nw\'\r\nUsing ex(1) with printf\r\n\r\nprintf \'%s\n\' \'$a\' \'foo bar baz\' . x | ex -s file.txt\r\nThe bash specific but more cryptic syntax $\' \' shell quoting and a herestring', '8', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('100', 'This is creative, but can you use a line of string instead of an input file? ', '4', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('101', 'dd conv=notruct oflag=append of=destination <<<\'Some string of text\'', '14', '12', '1', '2019-10-27 10:00:12', '0');
INSERT INTO `comment` VALUES ('102', 'Since no one has mentioned, this is another way to append text to a file.\r\nUse any text editor like vi, nano, vim. Follow below steps for vi and vim.', '12', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('103', 'As to the ok-ness or not, I\'d wager that it\'s more an aggression (and possibly a show-off) than a wish to be helpful. So it should be discouraged, yes. But privately, not publicly.', '7', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('104', 'Just to add some context. This happened to me (as the student). I was naive and it pained me to hear silence for a few seconds if the other student didn\'t know the answer. My lecturer took me into a side-room after class quietly and explained how it wasn\'t helping the class and he appreciated that I was aware, but to let the other students answer the questions. He advised that I don\'t answer any questions in the class, which actually changed my attitude for classes ever since that talk and I always took a back seat unless I was stuck/unsure.', '6', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('105', 'If a question gets answered that\'s good. Even more so by an engaged student. What would be your lesson to the student to stop answering questions? Respecting your authority? If that\'s the only reason for you to call him into a meeting, you should rethink your motives. Authority has to serve a purpose. ', '2', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('106', 'Following from @image, students can give better answers than professors, because they better understand their peers\' knowledge. ', '15', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('107', 'The way I understood the question, the professor wants to explain the context and required knowledge, so the student and his silent compatriots know, why the answer is correct. And the interrupting student only seems to be shouting out the factual answer, without explaining any underlying goings-on. Aside from the interruption of class and possible interpretation of the other students, this leaves a lot of learning on the table.', '9', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('108', 'This student\'s answers are generally correct. She comes across as very arrogant. Though. she is retaking my class because she got very low score last time. I overheard that she had studied this material from a teacher from School X (a top school) and it was way better than what\'s been done in this class. ', '2', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('109', 'Arrogance is painful, of course and reflects badly on her, I expect. I might lean, in such a case, as requiring a \"hand up\" first with explicit permission to speak.', '15', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('110', 'One thing that such a student fails to understand, of course, is that often the best answer is a minimal answer. An answer that lets students develop insight, not just get answers. Saying too much in answering a student question may be worse than saying nothing. ', '6', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('111', 'Buffy, I like your approach. A premature answer also robs me of the need to explore the question. Who else doesn\'t know? Why, are they missing context? Other audience members are less likely to admit to not knowing if the answer has already been given.', '9', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('112', 'That seems suspicious, so they have so little confidence in your teaching that they were able to take material from a class they weren\'t even taking at a completely different university and understand the material way better? If so It is not in the students best interest to not answer these questions because clearly they are gaining experience and study in what ever subject you are teaching, even if you feel it is best for the class. I thought it was just an overeager student, but given this new information I\'m afraid you may have inadvertently caused this. ', '12', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('113', 'If the answer is understood, then everyone is happy. If not, then I proceed to explain the answer in my own way.', '6', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('114', 'At the end of the day, the most important thing is that the students understand as much as they can, regardless of the person explaining. Of course, it is sometimes annoying for a student to interrupt your answer arrogantly. But you can always turn this situation into your advantage. Remember that there will be a question where someone else wants to answer, and then your lecture becomes interactive. Interactive lectures, in my opinion, are the best to follow and the most enjoyable ones.', '11', '12', '1', '2019-10-27 10:00:13', '0');
INSERT INTO `comment` VALUES ('115', 'As a student I always very much disliked having my questions answered by the class know-it-all rather than the professor. I could have an enjoyable interactive session (it wouldn\'t be a lecture) at the local coffee shop. I\'m paying tuition to hear material from a real professor.', '2', '12', '1', '2019-10-27 10:00:14', '0');
INSERT INTO `comment` VALUES ('116', 'You pay tuition to learn the promised material, as the tutors see fit. Other than that, your own motivation of paying money does not matter, unfortunately.', '10', '12', '1', '2019-10-27 10:00:14', '0');
INSERT INTO `comment` VALUES ('117', 'Have times when it is appropriate for students to answer each other\'s questions. It wasn\'t clear from your question whether your class has that, but if it doesn\'t, consider adding it. Everyone benefits -- some students get their questions answered, others get to think through the material more deeply, and everyone realizes that they can think and learn on their own, without everything coming from you.', '13', '12', '1', '2019-10-27 10:00:14', '0');
INSERT INTO `comment` VALUES ('118', 'I\'d say \"I need you to do X\" from an authority figure is a polite directive (imagine hearing it from your boss), but that will depend on cultural context.', '1', '12', '1', '2019-10-27 10:00:14', '0');
INSERT INTO `comment` VALUES ('119', 'I agree. I\'m just thinking someone could misinterpret\"make your request\" as something other than giving a polite directive, so that\'s the part I was suggesting to change; I think the actual wording you suggest could work well for the situation.', '7', '13', '1', '2019-10-27 10:00:17', '0');
INSERT INTO `comment` VALUES ('120', 'Recruit them as extraofficial help. Task them with answering questions in the online fora (official or non-official). Talk to them and work out some etiquette on answering questions in class: give others time to think the problem through, let others answer first, in general, be polite to co-students.', '13', '13', '1', '2019-10-27 10:00:17', '0');
INSERT INTO `comment` VALUES ('121', '\r\nAsk them/ tell them to sit at the back of the room.\r\n\r\nIt\'s always more effective to change the situational dynamics rather than to try to change the person. Some people will automatically try to join a conversation if they are in the middle of it. When out of the line of sight, they are less likely to interrupt.\r\n\r\nIt doesn\'t always work. But telling people to be silent doesn\'t always work either: this is an alternative strategy.', '13', '13', '1', '2019-10-27 10:00:17', '0');
INSERT INTO `comment` VALUES ('122', 'IMO this may (probably) come off as arrogant and things such as not everyone is taking the class for the third time are disrespectful to the student even if he or she is annoying. I\'m not sure this will help OP resolving this simple problem. ', '8', '13', '1', '2019-10-27 10:00:17', '0');
INSERT INTO `comment` VALUES ('123', 'PLEASE don\'t do this. If one of my profs did this to another student, it would instantly destroy my imagine of that prof permanently. And it might open the prof up to professional, civil, and even criminal complaints (e.g. FERPA violation). But beyond that, it\'s bullying/abusive due to the power differential between student and prof. Student disrupts class: small wrong against prof. Prof humiliates student publicly in front of their peers at a vulnerable social stage: MUCH larger wrong. Like a 300lb person punching an 80lb person\'s lights out over a slight irritation. PLEASE don\'t do this.', '4', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('124', 'Are you the user Guest? If so, I normally enjoy your answers (they are often better than most of this site\'s regulars) but this answer is just horror. –', '9', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('125', 'DateListPlot[ReplacePart[#, 1 -> Prepend[#[[1]], 2020]] & /@ data]', '12', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('126', 'Comments are not for extended discussion; this conversation has been moved to chat', '1', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('127', 'George VI of the United Kingdom served as a turret officer on HMS Collingwood and saw action at the Battle of Jutland, being mentioned in dispatches. This was of course before he became King.', '15', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('128', 'Most male British royals take parts in whatever conflicts Britain participates. I think the current young princes (potential heirs) served in Afganistan for some time.', '14', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('129', '首先，哪个熟悉用哪个。 齐次，个人推荐用 Python 写，效率高', '9', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('130', 'True. However immediate heirs are rarely sent to combat. Wills was not in combat, and Harry probably isn\'t going to be king. George VI was probably only allowed to fight because he wasn\'t supposed to be king either.', '16', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('131', 'Thank you for the answer. I should have been clearer: I meant while reigning. That said, presumably George VI actually fired a gun, from the sound of this?', '4', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('132', 'A turret officer would have been in command of one of the main guns of a battleship. So he would have been next to the gun and given the command to fire, though probably not actually pulled the \"trigger\" himself. That\'s definitely \"in combat\" from a navy point of view, and he is running exactly the same risks as any Ordinary Seaman.', '15', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('133', 'Good enough for me... although the main issue is still that he wasn’t reigning at this time.', '10', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('134', 'Now close? Napoleon would have had to be within 400 yards I expect to be hit by musket fire, even spent. ', '5', '13', '1', '2019-10-27 10:00:18', '0');
INSERT INTO `comment` VALUES ('135', 'Thanks for the answer. I would say this \"kind of counts\". Napoleon certainly wasn\'t a king, though he was an emperor (albeit not one of noble descent). Evidently he didn\'t make use of a weapon himself whilst Emperor of the French, though the fact he was wounded counts for something', '6', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('136', ' However, I believe your \"distinction\" between kings and emperors is misplaced. (1) To be meaningful, I believe you should be looking for sovereigns rather than monarchs. Those are the family lines held to be \"acceptable for royal marriage\" and would include the many houses of \"Imperial Princes\" in the H.R.E. (2) The proper title of the Hapsburg Emperors was King of the Romans, and for many centuries they were also King of Bohemia as a personal possession in addition to Carpathia.', '8', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('137', 'True, but it wasn’t what entitled him to be Emperor if the French, nit by a long shot.', '6', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('138', 'Thanks for the answer. Definitely not European though', '14', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('139', 'One could also argue more directly that\r\np(s,b)=s+(1−s)(1−p)p(s,b)\r\nThe \'probability to win if it is your turn\' equals the \'probability to win directly in one turn\' plus the \'probability to win if it is your turn\' times the \'probability to get two turns further\'. ', '5', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('140', 'Or another. In a particular turn (of two steps) either the first person wins with probability s, the second person wins with probability (1−s)b or nobody wins with probability (1−s)(1−b). The probability that the first person wins *conditional* on the game ending in the particular turn (of two steps) is\r\nss+(1−s)b\r\nand since this is independent from whatever turn the game ends it equals the probability to win the game in any turn. ', '5', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('141', 'Thank you for sharing those thoughts. I agree that these approaches will work here and may be the shortest, most elegant route to solving the present problem. For generalizations to games with more than two states, though, such as Penney\'s game (and other Markov chains), the straightforward method of considering each state is what generalizes.', '10', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('142', 'I get that the Markov chain approach is more general. But the symmetry approach with the elimination seemed a bit counterintuitive (cumbersome) to me. I did find it a fun approach however. Would there be problems when that works better? ', '3', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('143', 'It\'s a natural way to solve the problem after you have drawn a graph of the states and the transitions. I sketched this approach at stats.stackexchange.com/a/12196/919. One finds the numbers on the nodes (the expected times to reach a terminal node) by solving a comparable set of simultaneous equations, with one variable per node.', '15', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('144', 'I think you may have Bill and Sally backwards in your sim. I find that Bill\'s probability of winning is ≈0.488.\r\n\r\nBill\'s probability of winning on his first throw, call it p1 is 0.40. Bill\'s probability of winning on his second throw requires him to miss, Sally to miss, then Bill to hit, or\r\n\r\np2=(1−0.4)(1−0.7)0.4=(0.18)(0.4)\r\n\r\nSimilarly,\r\n\r\np3=(1−0.4)(1−0.7)(1−0.4)(1−0.7)0.4=(0.18)2(0.4)\r\n\r\nOr generally,\r\n\r\npi=(0.18)i−1(0.4)\r\n\r\nBill\'s overall probability of winning is Σpi.\r\n\r\nSince the ratio of sequential probabilities is constant, this is a geometric series. The sum of an infinite geometric series can be found with the formula\r\n\r\nΣri−1p1=p11−r=0.41−0.18=0.40.82≈0.4878', '1', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('145', 'For the first round, Bill wins with probability 0.6. For he to win on the second round, Sally needs to lose. Let Bi be the event that Bill wins at i-th trial; same for Sally (i.e. Si). So, for the second trial, we can write:\r\nP(B2)=P(B′1)P(S′1|B′1)P(B2|B′1,S′1)=0.6×0.3×0.4\r\n\r\nThis goes on similarly for each i, ending up with:\r\nP(Bill wins)=0.4(1+0.18+0.182+…)=0.41−0.18', '7', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('146', 'It seems easiest to do it as a recurrence relation.\r\n\r\nBill and Sally are going to alternate throwing. When Bill goes first, he will win immediately 40% of the time. The other 60% is like saying Sally goes first. In that case, Sally will win 70% of the time and the other 30% (of the 60%), we\'re back to the probability of Bill winning if he goes first.\r\n\r\np = 0.4 + 0.6 ( 0.3 * p)\r\n\r\nSolve for p, get p = 0.4 / 0.82 = 48.8%\r\n\r\nSomething\'s up with your simulation, or @CFD and I don\'t understand your problem statement.', '12', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('147', 'You are aware that the ESTA site is available in many languages, including French?', '5', '13', '1', '2019-10-27 10:00:19', '0');
INSERT INTO `comment` VALUES ('148', 'What is the actual question here? ', '2', '13', '1', '2019-10-27 10:00:20', '0');
INSERT INTO `comment` VALUES ('149', 'I think the real question is what does the ESTA question mean and why is it so poorly written? Having parsed the question several times myself it is very clearly ambiguous (wording intentional) and can be read several ways.', '10', '13', '1', '2019-10-27 10:00:20', '0');
INSERT INTO `comment` VALUES ('150', ' it was originally aimed at \"clearly ambiguous\" but I\'m not sure if your other interpretation is more amusing!', '11', '13', '1', '2019-10-27 10:00:20', '0');
INSERT INTO `comment` VALUES ('151', 'I can see an interpretation but only through the language barrier (I work with a large number of french speakers) so you might have a point. I\'m not active here so am not going to comment on whether it is on topic or not I only wanted to clarify the question. I think the officialese that is being used here is specific enough to travel.', '15', '13', '1', '2019-10-27 10:00:20', '0');
INSERT INTO `comment` VALUES ('152', 'This should be easier to answer. It sounds like in your case, where you are French citizens and have only ever been French citizens, the answer would be no. (If your husband was issued a French passport in Australia, that would not count as a different country. If he was issued an Australian passport, because he became an Australian citizen, that would be entirely different.)', '12', '13', '1', '2019-10-27 10:00:20', '0');
INSERT INTO `comment` VALUES ('153', 'The reason the \"or ID for travel\" is also in the question is because there are other kinds of documents (such as those issued to refugees) which are generically called \"travel documents\". These are documents that you could use for international travel in lieu of a passport.', '2', '14', '1', '2019-10-27 10:00:23', '0');
INSERT INTO `comment` VALUES ('154', 'Comments are not for extended discussion; this conversation has been moved to chat. You can post additional comments there. ', '13', '14', '1', '2019-10-27 10:00:23', '0');
INSERT INTO `comment` VALUES ('155', 'A passport issued in Australia is not necessarily issued by Australia. The key part of the question is \"by any other country.\" Another passport issued by the same country doesn\'t count, regardless of when or where it was issued.\r\nIf you and your husband have both held only French nationality then all your passports and national ID cards have been issued by France, and your answer to this question should be no.', '7', '14', '1', '2019-10-27 10:00:23', '0');
INSERT INTO `comment` VALUES ('156', 'Although this implies that your husband answered the question incorrectly, he probably should not apply for a new ESTA. Incorrect answers that disclose extra information are not particularly troubling because they are not deceptive.', '15', '14', '1', '2019-10-27 10:00:23', '0');
INSERT INTO `comment` VALUES ('157', '(Anyone who is in the opposite circumstances should probably submit a new application, however, because willfully omitting information that should have been included is deceptive; the omission could therefore lead to trouble; and disclosing the information on your own initiative is the best way to show that the earlier omission was not willful.)', '16', '14', '1', '2019-10-27 10:00:23', '0');
INSERT INTO `comment` VALUES ('158', 'The reason Voldemort hated his Muggle father was because his father left his mother to die when she was pregnant.', '20', '15', '1', '2019-10-27 11:25:42', '0');
INSERT INTO `comment` VALUES ('159', 'I thought Voldy hated old Tom because he was a muggle, and not because he abandoned Merope and baby Voldy.', '1', '15', '1', '2019-10-27 11:25:57', '0');
INSERT INTO `comment` VALUES ('160', 'That\'s actually the other way around. Voldy hated muggles because his father was a muggle.', '21', '14', '1', '2019-10-27 11:26:27', '0');
INSERT INTO `comment` VALUES ('161', 'Uhm, where was THAT in the books? Did JK Rowling cook up something new or is my memory failing me?', '3', '16', '1', '2019-10-27 12:25:17', '0');
INSERT INTO `comment` VALUES ('162', ' I\'m pretty sure this is all covered in the sixth book (though it doesn\'t actually use the word \"rape\").', '20', '16', '1', '2019-10-27 12:26:04', '0');
INSERT INTO `comment` VALUES ('163', 'I believe love potions are so common a trope in fantasy literature that it is easy as a reader to gloss over the fact that their real-world equivalent is a rape drug, or perhaps an aphrodisiac. Also a lot of instances of love potions are in childrens\' literature, which means sex isn\'t the goal, just mutual affection. ', '3', '16', '1', '2019-10-27 12:26:35', '0');
INSERT INTO `comment` VALUES ('164', 'It likely wouldn\'t have mattered. Psychologically, humans can hold entirely contradictory thoughts about the same subject. A good example, and somewhat analogous in this case, consider white supremacists. On the one hand, they\'re prone to believing how white Europeans are smarter and better than other people on the planet. But, at the same time, they think that Jews/non-whites secretly control everything and run it behind the scenes with elaborate, highly-sophisticated organizations. When you think about it, seems sort of contradictory to believe those two things, doesn\'t it?', '20', '16', '1', '2019-10-27 12:27:22', '0');
INSERT INTO `comment` VALUES ('165', 'So it could easily be the same for Voldemort. \"My Muggle father left my mother to die.My Muggle father was weak and fell victim to a simple spell.\" Simple enough rationalization to justify his hatred and loathing, even if someone looking at it objectively could understand that those two things could also be stated as \"My magic-using mother raped an innocent man who left his abuser in disgust when he could.\"', '10', '16', '1', '2019-10-27 12:27:54', '0');
INSERT INTO `comment` VALUES ('166', 'What you said is inherent in the second last sentence of the question (he killed his father knowingly). You just elaborated the question. You didn\'t answer: \"Did he know?\"', '13', '17', '1', '2019-10-28 10:00:04', '0');
INSERT INTO `comment` VALUES ('167', 'I agree. This is a great explanation how both possibilities exist (Voldemort might\'ve known, but acted nonetheless), however, the actual question is still left completely unaddressed. ', '13', '18', '1', '2019-10-28 10:00:07', '0');
INSERT INTO `comment` VALUES ('168', 'A foolish consistency is the hobgoblin of little minds.', '1', '18', '1', '2019-10-28 10:00:07', '0');
INSERT INTO `comment` VALUES ('169', 'That\'s exactly where my mind went too, though the exact shape of the rationalization I envisioned was closer to \"if my father wasn\'t a muggle he wouldn\'t have been vulnerable to this kind of stuff (and thus I would have never been abandoned by my father and grown up to with a dysfunctional lack of love and care for others as a protective mechanism for me being deeply hurt due to a lack of feeling loved and cared for)\", with the part in parentheses never quite reaching conscious self-awareness, but underpinning the motivating emotions. ', '20', '16', '1', '2019-10-29 22:21:03', '0');
INSERT INTO `comment` VALUES ('170', 'You think I was going to use my filthy Muggle father\'s name forever? I, in whose veins runs the blood of Salazar Slytherin himself, through my mother\'s side? I, keep the name of a foul, common Muggle, who abandoned me even before I was born, just because he found out his wife was a witch?', '26', '19', '1', '2019-10-30 14:59:53', '0');
INSERT INTO `comment` VALUES ('171', 'Furthermore, Tom was raised in an era where men were not typically viewed as victims in cases of sexual assault. Voldemort extensively researched his family history and might have guessed his father had been magically ensnared, but to recognize Tom Sr. as a victim goes against Voldemort\'s character. If he knew Tom Riddle Sr. was taken against his will, it would not have changed Voldemort\'s contempt for his Muggle parentage.', '20', '19', '1', '2019-10-30 15:00:15', '0');
INSERT INTO `comment` VALUES ('172', 'To add to your last point, you have to remember that Rowling\'s magical world is one where date rape drugs are not only legal, but encouraged for use in a high school setting. According to Rowling Voldy\'s mother did nothing wrong. ', '27', '20', '1', '2019-10-30 15:19:49', '0');
INSERT INTO `comment` VALUES ('173', 'Sorry, where is it encouraged? I remember the love potions popping up a few times, but only in reference to Fred and George and Voldermort\'s parents', '28', '21', '1', '2019-10-30 15:23:32', '0');
INSERT INTO `comment` VALUES ('174', 'By all appearances, that \"according to Rowling bit\" is incorrect.', '20', '21', '1', '2019-10-30 15:23:49', '0');
INSERT INTO `comment` VALUES ('175', 'That quote doesn\'t do anything to invalidate my comment. Really, it reinforces it by her refusal to outright condemn love potions. While obviously her characters aren\'t her herself, no one forced her to use rape as a punchline, and especially not to mock and ridicule male rape survivors.', '21', '9', '1', '2019-11-15 15:34:10', '0');
INSERT INTO `comment` VALUES ('176', 'Your comment says that Rowling claims that Merope did nothing wrong. Not only can I not find any instance of her saying that, I link to a quote where she says that it was coercion. If your argument is that she didn\'t go far enough, maybe it would make more sense to say that, because she never seems to have said what you\'re asserting. She\'s said a lot of other bad things, but that\'s not one of them, so far as I can tell.', '8', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('177', 'Divide the grid into regions by drawing along some of the dotted lines.\r\nEach region should have one group of gray cells and one group of white cells; both of these groups should be connected.\r\nThe two groups in a region should be the same size and shape (but they may be rotated or reflected).\r\nEach number tells the size of each of the groups in its region.', '6', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('178', 'Do the regions have to cover every square on the grid?', '12', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('179', 'Now, we focus on the 4 region in the lower right. Clearly, it must use white squares in the bottom right, but it cannot divide that area of the grid into two, otherwise there will be isolated regions of white squares. Thus, the only way to construct the 4 is to take the white squares in an L-shape, just straddling the edge of the grid. This will also force the construction of the 2 region in the bottom right', '1', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('180', 'This leaves us with a long L-shaped white square block in the bottom right that is 3 squares wide and at least 5 squares tall. There is only one way to fit such a shape into the black squares and have it connect to the white squares, as shown:\r\n', '4', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('181', 'Note that the above construction also forces the construction of the remainder of the 4 region. At this point, we are pretty much home free, as the remainder of the deductions are fairly intuitive. First, complete the upper left portion:\r\n', '16', '22', '1', '2019-11-17 10:00:05', '0');
INSERT INTO `comment` VALUES ('182', 'ok let me think', '1', '68', '1', '2020-02-16 01:07:31', '0');
INSERT INTO `comment` VALUES ('183', 'You can use the fgets() function to read the file line by line:\r\n$handle = fopen(&quot;inputfile.txt&quot;, &quot;r&quot;);\r\nif ($handle) {\r\n    while (($line = fgets($handle)) !== false) {\r\n        // process the line read.\r\n    }\r\n    fclose($handle);\r\n} else {\r\n    // error opening the file.\r\n} ', '2', '72', '1', '2020-03-03 18:26:02', '0');
INSERT INTO `comment` VALUES ('184', 'i want this answer too', '4', '72', '1', '2020-03-13 19:27:09', '0');
INSERT INTO `comment` VALUES ('185', 'i aslo want this question', '4', '69', '1', '2020-04-05 12:29:13', '0');
INSERT INTO `comment` VALUES ('186', 'i aslo want this question', '4', '54', '1', '2020-04-05 12:29:27', '0');
INSERT INTO `comment` VALUES ('187', 'i aslo want this question', '4', '61', '1', '2020-04-05 12:29:39', '0');
INSERT INTO `comment` VALUES ('188', 'i aslo want this question', '13', '50', '1', '2020-04-05 12:30:30', '0');
INSERT INTO `comment` VALUES ('189', 'i aslo want this question', '13', '50', '1', '2020-04-05 12:30:34', '0');
INSERT INTO `comment` VALUES ('190', 'i aslo want this question', '13', '64', '1', '2020-04-05 12:30:47', '0');
INSERT INTO `comment` VALUES ('191', 'i aslo want this question', '13', '71', '1', '2020-04-05 12:31:01', '0');
INSERT INTO `comment` VALUES ('192', 'i aslo want this question', '1', '61', '1', '2020-04-05 12:31:21', '0');
