/*
Navicat MySQL Data Transfer

Source Server         : ll
Source Server Version : 50722
Source Host           : localhost:3306
Source Database       : qa

Target Server Type    : MYSQL
Target Server Version : 50722
File Encoding         : 65001

Date: 2020-05-24 13:49:21
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `content` text,
  `user_id` int(11) NOT NULL,
  `created_date` datetime NOT NULL,
  `comment_count` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `date_index` (`created_date`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of question
-- ----------------------------
INSERT INTO `question` VALUES ('1', 'How can I make a blue layer, which blurs everyting that it is behind one?', 'I\'ve got a , which should blur everything which is behind him. How can I make it with CSS only?', '3', '2019-10-21 10:13:24', '0');
INSERT INTO `question` VALUES ('2', 'How to display dynamic array of object in table under react native app?', 'I\'m building a react native app, moving from home screen to setting screen, i need to load a dynamic array in table format. Right now im using compoundDidMount() function to fetch data from an api. Everything is fine but i don\'t know how to render the output array i got from compoundidmount function.', '1', '2019-10-21 20:12:02', '2');
INSERT INTO `question` VALUES ('3', 'set entire column to zero and then update a specific row', 'I want firstly antire def column set to be 0 except the row where id is a variable (this should be 1).', '5', '2019-10-22 20:24:55', '0');
INSERT INTO `question` VALUES ('4', 'Permission denied for openFileDescriptor to pass a file from SDCARD to FFmpeg', 'Permission denied for openFileDescriptor to pass a file from SDCARD to FFmpeg\r\nI am trying to work with a file from Sdcard which is to be passed to FFmpeg fro this I am using', '5', '2019-10-22 20:30:11', '3');
INSERT INTO `question` VALUES ('5', 'Permission denied for openFileDescriptor to pass a file from SDCARD to FFmpeg', 'Permission denied for openFileDescriptor to pass a file from SDCARD to FFmpeg\r\nI am trying to work with a file from Sdcard which is to be passed to FFmpeg fro this I am using', '3', '2019-10-23 10:00:05', '17');
INSERT INTO `question` VALUES ('6', 'IPython: ipywidgets bug - Code working on Goolge Colab, but not on Jupyter Notebook (tested on 2 different PCs)?', 'This code is a \"Filter as you type\" textbox example. It works fine on Google Colab, but not on Jupyter Notebook. I tried it on 2 different computers (and on 2 different browsers) that have Jupyter Notebook installed and the \'out\' widget only displays the textbox but nothing else. Any idea how to fix this?\r\n\r\nI have tried pip uninstall ipywidgets then install again without success.\r\n\r\nThanks.', '20', '2019-10-24 16:13:50', '0');
INSERT INTO `question` VALUES ('7', 'How to change label value based on two dropdown list in jquery', '` $(document).ready(function(){ $(\"#method,#paper\").on(\"change\", function(){', '20', '2019-10-24 16:14:00', '0');
INSERT INTO `question` VALUES ('8', 'Lambda Calculus vs Category theory in FP', 'Trying to learn functional programming approach I faced both lambda calculus and Category theory terms. \r\nCould you please explain in layman\'s terms what the differences between them in the scope of FP. \r\nWhat do they mean for FP? \r\nThank you!', '20', '2019-10-24 16:14:14', '0');
INSERT INTO `question` VALUES ('9', 'Counting the number of repeated letters in a string', 'Please suggest some method so that I can get the expected output. Any help will be highly appreciated.', '20', '2019-10-24 16:14:28', '43');
INSERT INTO `question` VALUES ('10', 'Forbidden 403 You don\'t have permission to access this resource. (mod_wsgi, wamp, apache2.4, django) on windows', 'i have installed everything properly and gone through all solutions related to this subject but still error remains, I\'m new to Django and i would really appreciate your help\r\n\r\nI get this error in my error log file:\r\n\r\n[Fri Feb 14 21:52:16.916422 2020] [authz_core:error] [pid 4288:tid 1252] [client ::1:51391] AH01630: client denied by server configuration: E:/AppSource/eCommerce/src/ecommerce/wsgi_windows.py\r\n\r\nand when i try to reach 127.0.0.1:80 i get: Forbidden 403\r\n\r\nand this is my wsgi_windows.py configuration:', '16', '2019-10-27 10:00:04', '0');
INSERT INTO `question` VALUES ('11', 'Function that changes the cell color', 'I am creating a function where if a cell has Yellow color and if I enter 0 in that cell, then it pops up a message box Red then colors the cell Red. And then if I enter 1 it reverts the color to Yellow.\r\n\r\nHere\'s my code:', '9', '2019-10-27 10:00:07', '7');
INSERT INTO `question` VALUES ('12', 'How do I update a combo box on an MS-Access form when the value of another combo box on that form is modified?', 'I am developing an MS-Access application. The database contains an Activity table that has two fields to identify the location where the Activity occurred: StateID and CityID. Both fields are foreign keys to other tables (State and City). The City table has a foreign key to the State table, pointing to the State that contains that City.\r\n\r\nI have an Activity form based on the Activity table. The form contains two combo boxes, one for StateID and one for CityID. I would like the user to select either the State or a City where the Activity occurred. If user just selects a State without specifying a city, no problem. However, if the user selects a City, I would like to update the StateID field with the State where that City is located. That would require an query on the City table to find it\'s related State.\r\n\r\nHow can I update the StateID field on the Activity table when the CityID combo box is updated? At the same time I would like to refresh the form so that that State appears in the State combo box.\r\n\r\nCan anyone help me?', '10', '2019-10-27 10:00:11', '31');
INSERT INTO `question` VALUES ('13', 'Connect to Ignite Cluster over SSL using JDBC Thin Client', 'Though, I\'ve setup SSL between all Ignite Nodes and whole Ignite Cluster is secured, I\'m able to access the data through JDBC thin client without passing any SSL configs. Does it mean though the cluster is secured we can connect without passing any ssl config/cert?\r\n\r\nI want no one can connect to the Ignite Cluster until and unless required ssl certs provided, is that possible to achieve?', '3', '2019-10-27 10:00:17', '34');
INSERT INTO `question` VALUES ('14', 'Cannot insert veries to mysql database', 'i created a table to my database and i want to add very to it. I use mysqli and my query is that;', '16', '2019-10-27 10:00:23', '6');
INSERT INTO `question` VALUES ('15', 'Why is file not being written to Android internal storage?', 'I am trying to create a text file and fill it with some data. Exception is being generated as shown in the code below. The file isn\'t getting saved and exception is generated. What is wrong with my code?', '21', '2019-10-27 11:25:16', '2');
INSERT INTO `question` VALUES ('16', 'Route:list works in local machine but gives error on server in laravel', 'I was updating my server code and everything worked well, even the migration and seeding.\r\n\r\nbut when I tried login URL it gave me 404 error so I checked and in that process ran then PHP artisan route: list command in the terminal.\r\n\r\nand got the error as below:', '22', '2019-10-27 12:24:52', '6');
INSERT INTO `question` VALUES ('17', 'Firstline not working in extension package.json', '0\r\nI am making an extension and firstline does not work. When I add', '16', '2019-10-28 10:00:04', '1');
INSERT INTO `question` VALUES ('18', 'Why I get only one element in slot inside v-for?', 'In my vue application code, I have a swiper component. inside this component I have a v-for and a slot.\r\n\r\nIn the parent component (Foo) I need to catch the component (baz) I put into slot, by ref. the problem is its return only one element not array as I though so.\r\n\r\nHow to keep this shape of components and still get the array I expected? is it possible?', '13', '2019-10-28 10:00:07', '2');
INSERT INTO `question` VALUES ('19', 'python override a api class method with different name', 'first, create my own class object inherit the api\r\n\r\nclass mainobject1(XAPI):\r\n    def __init__(self):\r\n        XAPI.__init__(self)\r\n        self.count = 0\r\n        # built-in to run api\r\n        self.run()\r\n    # default api method name\r\n    def error(self, regId, errorCode, errorString):\r\n        print(\"Error:\", errorCode)\r\n        self.count += 1\r\nthis allows me to access self.count in \"error\" method, but is it possible to direct the API method \"error\" to other specific name like \"xapi_error\"? there are few api in my program so I wanna declare them clearly. i simply do not want self.error be accessible in mainobject class.\r\n\r\nso, create an api object separately', '26', '2019-10-30 14:59:20', '2');
INSERT INTO `question` VALUES ('20', 'Error in pkg-config when try to download git repository?', 'I was trying to make a facial recognition app using golang and Kagami/go-face repository. It requires dlib-models. And I was used MSYS tool for get the distribution in windows. But when i try to get the go repository using \"go get github.com/Kagami/go-face\" command and it gives an error - \"# pkg-config --cflags -- dlib-1\" .\r\n\r\nAny one had this issue before in windows 10.', '27', '2019-10-30 15:19:23', '1');
INSERT INTO `question` VALUES ('21', 'Need help on how to use the .split and .lower python string methods\r\n', 'The input: a. Use the input function and have one prompt that asks the user to enter a last name, or a first and last name (separated by whitespace). It should print an error if no names are given or more than two are given. b. The program should work if the user enters names in uppercase, lowercase, or a mix of case. Since the names in the file phones.txt are of mixed case, for comparisons, you’ll want to make use of the string method .lower() to convert both the input strings and those read from the file to lowercase. c. Use the string .split() method on the input to split it into a list of strings, then assign the input to string variables first_name and last_name based on whether the length of the string is one element or two. Also convert the strings to lower case using .lower().\r\n\r\nOpen phones.txt and loop through each line in the file to see if it matches the provided input. When a match is found, display the output in the following format:\r\n\r\n(first name) (last name), (phone number)\r\n\r\nHere is what I have so far:', '28', '2019-10-30 15:23:18', '2');
INSERT INTO `question` VALUES ('22', 'How to recieve messages for offline clients using QoS MQTT in eclipse-mosquitto?', 'My mosquitto.conf is (This is the entire conf file since everything else is just commented out)\r\n\r\nlog_dest file /mosquitto/log/mosquitto.log\r\nlog_type all\r\nconnection_messages true\r\nlog_timestamp true\r\nlog_timestamp_format [%H:%M:%S]\r\npersistence true\r\npersistence_location /mosquitto/data/\r\nlistener 1883\r\nlistener 9001\r\nprotocol websockets\r\nThen i run', '11', '2019-11-17 10:00:04', '11');
INSERT INTO `question` VALUES ('23', 'MS SQL DB insert problem. Data insert operation is successful but after closing the application and re open it that data can not be found [duplicate]', 'I am trying to make a C# application which will have an attached DB . So I did an insert operation which is working perfectly and after insert operation I can see my data at data grid view . but after closing the application I saw that my data table is empty . so I re opened my application and saw that the data grid view is also empty . Here is my sample code : Insert', '9', '2019-11-17 10:00:15', '75');
INSERT INTO `question` VALUES ('24', 'java.io.IOException: CreateProcess error=740, The requested operation requires elevation when running the jobs through jenkins\r\n', 'This issue has been seen when we build the job, however i have added the ssh key for git but still failed to build the job\r\n\r\nIs there anything i need to add it in specific, please do help me to get it resolved', '4', '2019-11-17 10:00:24', '10');
INSERT INTO `question` VALUES ('25', 'Big Query Data Expiration', 'I have been collecting data in Big query for analysis purposes. However, the size of the data is growing and I only need 2 weeks of recent data. I wanted to erase data that is not used. I did some research and I found out that there is expiration option which partitioned data.\r\n\r\nCurrent setup My table is a partitioned table I insert my data from my lambda function with code similar to this (I have tried adding timePartitioning option, but it didn\'t work so that\'s why I am asking on stackoverflow if anyone knows)', '5', '2019-11-17 10:00:28', '34');
INSERT INTO `question` VALUES ('26', 'How to write length function for all Monoids', 'I\'m playing around with rewriting simple functions in different ways and I clearly misunderstand some core concepts. Is there a better way to work with limited types like these?', '13', '2019-11-17 10:00:33', '15');
INSERT INTO `question` VALUES ('27', 'How Add ViewHolder For A GrideView List in Android\r\n', 'i\'m Tryed to write a ViewHolder for this gridView list but i get error every time\'s . can you tel me how make a right ViewHolder for this gridView list?\r\nmy code:', '15', '2019-11-17 10:00:38', '2');
INSERT INTO `question` VALUES ('28', 'Angular 8 custom framework\r\n', 'I wanted to design and develop a framework on top of Angular 8/9 which should serve for multiple applications which can share common code across all the applications.\r\n\r\nThis application serves for various countries, the rules from country to country may same or differ.\r\n\r\nUI-Components: custom UI components which is exposed as node module, In future which can be upgraded and published to all the apps. Core : which should have common, core, abstract code for all the applications.\r\n\r\nCountry-1 code : Country-1 is Implementation of Core, which will reuse and extend them where ever required.\r\n\r\nCountry-N code : Country-N is Implementation of Core, which will reuse and extend them where ever required.', '12', '2019-11-17 10:00:41', '7');
INSERT INTO `question` VALUES ('29', 'Do I need to unsubscribe the Observable within a Promise?', 'Do I need to unsubscribe any of the above Observables? What does take(1) really do? Lastly, how do you use async-await in this context? (Is it better to use async-await?)\r\n\r\nNew to Angular. Please help. Thank you.', '13', '2019-11-17 10:00:44', '14');
INSERT INTO `question` VALUES ('30', 'How can I play video from FTP server to my website?', 'I am working on a project where the there is a requirement to play video from ftp server in the website. I am not sure how can I do this, but I am trying. This is a CodeIgniter project. What I am doing is that I am connecting to the ftp server using username and password, fetching the video file names and giving it to the video source which is like doing it for playing video using http protocol. I am not sure how to play the video from the source as it\'s all ftp link. Also there is authorization. I have done some research on that but I did not find anything useful. Can somebody please help?', '21', '2019-11-17 13:31:23', '1');
INSERT INTO `question` VALUES ('31', 'Access structure members by using structure name only', 'I don\'t know what type on question i am asking.but i only need suggestion or idea to find the way.\r\n\r\nI have many structure with large number of members like below', '13', '2019-11-18 09:43:58', '0');
INSERT INTO `question` VALUES ('32', 'Laravel npm run debug invalid regular expression invalid group error', ' SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](lodash|jquery|axios|vue)[\\/]/: Invalid group\r\n            at RegExp (native)\r\n            at Extract.createCacheGroup (/home/wwwroot/default/blog/node_modules/laravel-mix/src/components/Extract.js:104:25)\r\n            at Extract.createSplitChunks (/home/wwwroot/default/blog/node_modules/laravel-mix/src/components/Extract.js:86:61)\r\n            at Extract.config (/home/wwwroot/default/blog/node_modules/laravel-mix/src/components/Extract.js:76:35)\r\n            at Extract.webpackConfig (/home/wwwroot/default/blog/node_modules/laravel-mix/src/components/Extract.js:60:59)\r\n            at Mix.listen.config (/home/wwwroot/default/blog/node_modules/laravel-mix/src/components/ComponentFactory.js:75:54)', '15', '2019-11-18 10:00:04', '12');
INSERT INTO `question` VALUES ('33', 'Product verification startup [closed]', 'I want each product have a random serial number like 645836846084 which would be print on product. The customer would send the number to a toll-free number to verify the product is genuine or fake by receiving an SMS. How much would the cost of designing such system. Good examples are Sproxil and Mpedigree. Please guide me', '1', '2019-11-18 10:00:08', '16');
INSERT INTO `question` VALUES ('34', 'How to write this IF statement in Linear programming with Big-M', 'I have to define a variable based on the decision variable (Var[i]), this is what I want to express: if var[i] >= 0, b[i] = 1.08; else b[i] = 0.91 What I wrote was :\r\n\r\nvar=LpVariable.dicts(\"Var\", df.index, lowBound=-2, upBound=2, cat=\"Continuous\")\r\n\r\nb={}\r\nfor i in df.index:\r\n    if var[i] >= 0.0:\r\n       b[i] = 1.08\r\n    else:\r\n       b[i] = 0.91\r\nHowever, it turned out that all b[i] were 1.08...; I searched for the problems, and found that it should be repleced by Big M method. But I still can\'t catch how to derive it.', '2', '2019-11-18 10:00:13', '0');
INSERT INTO `question` VALUES ('35', 'Populating table with textbox value from previous HTML page\r\n', 'I have some JS that stores the name and value of selected checkboxes on one page and then, on a button click, adds this data to a table on page 2.\r\n\r\nThis works, but now I am looking to do the same for a textbox containing a number. Specifically, I\'m looking to take the value entered by the user and add this to a cell in the table. What would be the best way to approach this? Add to the existing function or create a separate on button click function specifically for the textbox value?\r\n\r\nHere\'s what I have so far:\r\n\r\nHTML for textbox:', '13', '2019-11-18 10:00:16', '10');
INSERT INTO `question` VALUES ('36', 'Java: Error “java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $”', 'I am trying to post user information to MYSQL database by Retrofit2. I am taking the information by edittexts, then passing them as a User object by retrofit. My server-side codes are written by php which is working nicely independently. I have checked it by postman.', '3', '2019-11-18 10:00:20', '30');
INSERT INTO `question` VALUES ('37', 'Change Input Value Jquery', 'Please help me, I want the value to change if I change the value in the text box . please see the picture enter image description here\r\n\r\nthis is my code :', '7', '2019-11-18 10:00:26', '16');
INSERT INTO `question` VALUES ('38', 'How can using DocProperty in MS-Word Fields as array form?', 'Array form MS-Word properties', '14', '2019-11-18 10:00:31', '17');
INSERT INTO `question` VALUES ('39', 'How can i extend a public variable from Multiboxtracker to another class?(Tensorflow Lite)', 'I am trying to get the title from Multiboxtracker class to Another Class Like Gettitle but i can\'t seem to be able to extend the public variable. Please help me out.', '8', '2019-11-18 10:00:38', '5');
INSERT INTO `question` VALUES ('40', 'Which one has more career prospects Lit-Element/Polymer 3 vs React vs Angular as per the latest trends in the market?', 'Experts, Can I have your attention please! As Lit-element is very new in the market, So, could not find anything around this.\r\n\r\nThanks!', '1', '2019-11-18 10:00:42', '0');
INSERT INTO `question` VALUES ('41', 'how to I get value of excel using C#, if a cell has error', 'For e.g., a cell with =1-b would have #Name error, but if I use .Value, it would return -2146826259, if I use .Text, it would return #Name, how could I get =1-b? Thanks in prior.', '12', '2019-11-18 10:00:44', '10');
INSERT INTO `question` VALUES ('42', 'show values on bar chart in Python', 'I would like to show a value for each column in my bar chart. What is the easiest way to do this please?', '5', '2019-11-18 10:00:49', '2');
INSERT INTO `question` VALUES ('43', 'Is a codepush deployment key considered sensitive?', 'I was wondering if the deployment key used to hit endpoints such as https://codepush.azurewebsites.net/updateCheck?deploymentKey=XXXis considered sensitive, or if it\'s safe to ship with the application. Can any malicious actions be performed with it?', '12', '2019-11-18 10:00:52', '16');
INSERT INTO `question` VALUES ('44', 'How to show preview of dragged and dropped image in angular?', 'I\'m trying to show the preview of an image that is dragged and dropped in angular.\r\n\r\nhospital.component.html', '14', '2019-11-18 10:00:57', '21');
INSERT INTO `question` VALUES ('45', 'import module in Class but module not defined in class method', 'In my python script, I\'m trying to import module in class and use the imported moudle in the class method.', '3', '2019-11-18 10:01:02', '21');
INSERT INTO `question` VALUES ('46', 'Looping js file via a url using foreach php mvc', 'This is the class for calling:\r\n$this->view->js = array(\"dashboard/js/default.js\");\r\n\r\nThis is my code included in header', '10', '2019-11-18 10:01:09', '7');
INSERT INTO `question` VALUES ('47', 'How to avoid delay while sending mouse inputs inside mouse hook proc?', 'It should simulate right click when I\'m clicking one of the mouse side buttons. The problem is that right mouse click triggers after a short delay (~400ms), not instantly. If I modify this code to call InputRButton... functions in keyboard hook proc instead of mouse hook proc, it works without any delays. Where\'s my mistake and how to fix it?', '7', '2019-11-18 10:01:12', '12');
INSERT INTO `question` VALUES ('48', 'Pandas: DeprecationWarning: elementwise comparison failed', 'I\'m trying to apply an expanding function to a pandas dataframe by group, but first filtering out all zeroes as well as the last value of each group. The code below does exactly what I need, but is a bit too slow:', '7', '2019-11-18 10:01:17', '29');
INSERT INTO `question` VALUES ('49', 'Efficient method for converting strings inside dataframes into arrays', 'I\'m working with a dataset of multiple CSV tables. One of these tables which consists of two columns has floating-point arrays with 512 elements in the form of strings. The table is quite large, so I was wondering if there is any efficient method for transforming them into actual arrays in the form of columns, instead of simply iterating over the records.\r\n\r\nThe shape of the original Table: (A few million records, 2)\r\n\r\nThe desired output shape: (A few million records, 513) Or maybe (A few million records, 2) but now the second column contains NumPy arrays and not strings.', '12', '2019-11-18 10:01:23', '5');
INSERT INTO `question` VALUES ('50', 'How to escape > and < in the regular expression? I have done with all the characters using (back slash) but unable to do it for <>', '<> or <> can you please help me for this. I have tried a lot.', '2', '2019-11-18 10:01:26', '2');
INSERT INTO `question` VALUES ('51', 'Is there a way of using Gremlin within an asyncio Python application?', 'The TinkerPop documentation describes GLV for Python. However, the examples presented in there are built around synchronous code. There is the aiogremlin library that was desingned to enable use of Gremlin in Python\'s asyncio code. Unfortunately, the project seem to be discontinued.\r\n\r\nDoes the official GLV support the asyncio or is there a way to use Gremlin in asynchronous Python applications?', '7', '2019-11-18 10:01:35', '4');
INSERT INTO `question` VALUES ('52', 'Idiom for handling size_t underflow in loop condition', 'In C and C++, size_t is an unsigned type that is used for expressing size. It expresses intent and somewhat simplifies range assertions (len < upper_bound vs len >= 0 && len < upper_bound for signed integers).\r\n\r\nBut every so often I mess up the edge cases.\r\n\r\n(In all the examples below len means the length of the array a).\r\n\r\nThe canonical example is a loop that iterates backwards. This code underflows for len=0.', '9', '2019-11-19 10:00:16', '51');
INSERT INTO `question` VALUES ('53', 'Google embed map place card responsive issue', 'I added map-responsive class to make responsive my google map in website but when I\'m resizing computer\'s screen, class place-card-large automatically turns to place-card-medium and the place card box is getting shorter in mobile view. I want to show full box of place card in mobile view as well.[enter image description here][1]', '5', '2019-11-19 10:00:27', '3');
INSERT INTO `question` VALUES ('54', 'How can i get calories data from any health band?', 'I work on some application that using calories data.\r\n\r\nI want get this data from any health bands that can be connect to android or ios phones.\r\n\r\nthe exact problem is that i don\'t want use google fit api or ios health kit and i want get data directly from hardwares and no matter what company build that.\r\n\r\nPlease help me.Thanks', '12', '2019-11-19 10:00:31', '1');
INSERT INTO `question` VALUES ('55', 'Security Measures to be taken while using Forms Authentication', 'I need help with the security measures to be taken while implementing forms authentication in asp.net webforms\r\n\r\nIn fact I\'m using a mix of forms and windows authentication for a login page i.e authentication method is forms and the user has to enter windows credentials to login.\r\n\r\nAny help would be greatly appreciated.', '14', '2019-11-19 10:00:39', '0');
INSERT INTO `question` VALUES ('56', 'Receive all data from TCP client in python', 'I am using SICK LMS400 Scaneer and using Python Code for TCP client to send instructions.\r\n\r\nReference: https://github.com/danieltak/py-LMS-sick-telegram-example/blob/master/LMS%20Example%201.py\r\n\r\nI am successfully able to Switch my sensor ON and OFF by sending Telegram message instructions. But, I am not able to fetch all the received message in my python window. The expected, output message I want to received is continuous', '8', '2019-11-19 10:00:42', '41');
INSERT INTO `question` VALUES ('57', 'Want to add regex in SQL Server check constraints to input only characters not any number even not include any number in character', 'I want to add a regex to a SQL Server check constraint to input only characters not any number even not include any number in character. Actually I want to input only [a-zA-Z] without mixing or including any numbers.\r\n\r\nPlease help anybody to provide that regex.', '7', '2019-11-19 10:00:50', '23');
INSERT INTO `question` VALUES ('58', 'vuetify textfield rules displaying error even after condition is statisfied', 'now when i add the same time in fromtime and totime. So the hours and minutes textfield hints should show 0hrs and 0mins. But it says min is required. The fromtime and totime textfield should be shown when detailedwd = 1. But when the detailedwd = 0, only hours and minutes textfield should be shown and when i enter 0 in hours and minutes textfield it does not show any error.', '5', '2019-11-19 10:00:56', '19');
INSERT INTO `question` VALUES ('59', 'Hibernate Flush Mode', 'I am using hibernate flush mode as MANUAL. But save method is executing insert method though I am not calling session.flush() method. I am using hibernate 5.2.12 and mysql dirver 8.0.6\r\n\r\nOutput is below:\r\n Hibernate: \r\n   insert into  person (first_name, last_name) values (?, ?) \r\n Hibernate: \r\n   select count(*) from Person \r\n Total records are= 5', '3', '2019-11-19 10:01:02', '40');
INSERT INTO `question` VALUES ('60', 'Image stretch on Macbook / Safari, all screen sizes', 'The page with the issue: https://www.fastforwardcomposites.com/foiling-luxury-catamaran-eagle-class\r\n\r\nMy client is experiencing stretched images on Safari or Mac OS/Macbook only. I can\'t test why or fix it because I do not own a Mac. Wondering if there is anything I can do that fits within my code to prevent image stretch WHILE keeping the aspect ratio of the pictures and scaling up and down correctly on all screen sizes. I have set the width to a %, and the height to \"auto\". The code in question is a little long because it is housed inside a big tabbed content area, but you can safely assume any images that I\'ve styled to be responsive within the tabs are stretching poorly on Mac (you can ignore the gallery tab, that\'s working fine).\r\n\r\nIs there any way to set the images to be responsive and snap down to fit the size of the container as the screen is resized on Safari without using set px values? Or is my only option to set the images to a specific PX height and width for every single possible screen size? I\'d obviously like to avoid that, as the images are already responsive and resize quite nicely on all other browsers and OS. Thanks guys!', '1', '2019-11-19 10:01:11', '78');
INSERT INTO `question` VALUES ('61', 'windows 10 integrated webcam option is not available under imaging devices', 'I could not find integrated web cam option under imaging devices. I have tried to install windows integrated driver again, but it did not work. Could you please provide solution, how we can resolve the issue.', '15', '2019-11-19 10:01:22', '2');
INSERT INTO `question` VALUES ('62', 'Tibco MFT internet server installation issue', 'I am trying to install Tibco MFT internet server but at step 9 I got stuck. The cmd screen is either vanishing after step 9 of installation or giving installation failure message. Can anyone please help me with this?', '10', '2019-11-19 10:01:30', '65');
INSERT INTO `question` VALUES ('63', 'Image stretch on Macbook / Safari, all screen sizes', 'The page with the issue: https://www.fastforwardcomposites.com/foiling-luxury-catamaran-eagle-class\r\n\r\nMy client is experiencing stretched images on Safari or Mac OS/Macbook only. I can\'t test why or fix it because I do not own a Mac. Wondering if there is anything I can do that fits within my code to prevent image stretch WHILE keeping the aspect ratio of the pictures and scaling up and down correctly on all screen sizes. I have set the width to a %, and the height to \"auto\". The code in question is a little long because it is housed inside a big tabbed content area, but you can safely assume any images that I\'ve styled to be responsive within the tabs are stretching poorly on Mac (you can ignore the gallery tab, that\'s working fine).\r\n\r\nIs there any way to set the images to be responsive and snap down to fit the size of the container as the screen is resized on Safari without using set px values? Or is my only option to set the images to a specific PX height and width for every single possible screen size? I\'d obviously like to avoid that, as the images are already responsive and resize quite nicely on all other browsers and OS. Thanks guys!', '1', '2019-11-19 10:01:41', '33');
INSERT INTO `question` VALUES ('64', 'windows 10 integrated webcam option is not available under imaging devices', 'I could not find integrated web cam option under imaging devices. I have tried to install windows integrated driver again, but it did not work. Could you please provide solution, how we can resolve the issue.', '7', '2019-11-19 10:01:47', '1');
INSERT INTO `question` VALUES ('65', 'Tibco MFT internet server installation issue', 'I am trying to install Tibco MFT internet server but at step 9 I got stuck. The cmd screen is either vanishing after step 9 of installation or giving installation failure message. Can anyone please help me with this?', '5', '2019-11-19 10:01:59', '50');
INSERT INTO `question` VALUES ('66', 'Automatically logout after refreshing the page in laravel 6', 'I am Automatically logout after refreshing the page in laravel 6. Everything is working fine but I am successfully logged in but when I refresh the page automatically logged out. I am using a socialite package to login to my app. I also increase the session lifetime to 180 in config/session.php file but still didn\'t work..', '14', '2019-11-19 10:02:07', '5');
INSERT INTO `question` VALUES ('67', 'lazy loading vs eager loading for nested comment system', 'I have a page that has a question and six comments (parent and children). Under lazy loading Laravel makes exactly 12 mysql queries. I\'d like to believe that it\'s not the best way to go about it. As the comments grow, this may introduce a problem. Take a look:', '9', '2019-11-19 10:02:11', '4');
INSERT INTO `question` VALUES ('68', 'Left Join two or more Schemas using mongoose', 'let UserSchema = new Schema({\r\n  name: {type: String, required: true}`\r\n});\r\n\r\nlet BookSchema = new Schema({\r\n  user_id: {type: Schema.Types.ObjectId, ref: \'Users\'},`\r\n  book: {type: String, required: true}\r\n});\r\n\r\nlet Users = mongoose.model(\'Users\', UserSchema);\r\nlet Books = mongoose.model(\'Books\', BookSchema);', '1', '2019-11-19 10:02:16', '1');
INSERT INTO `question` VALUES ('69', 'Is it true that in multiprocessing, each process gets it\'s own GIL in CPython? How different is that from creating new runtimes?', 'Are there any caveats to it? I have a few questions related to it.\r\n\r\nHow costly is it to create more GILs? Is it any different from creating a separate python runtime? Once a new GIL is created, will it create everything (objects, variables, stack, heap) from scratch as required in that process or a copy of everything in the present heap and the stack is created? (Garbage collection would malfunction if they are working on same objects.) Are the pieces of code being executed also copied to new CPU cores? Also can i relate one GIL to one CPU core?\r\n\r\nNow copying things is a fairly CPU intensive task (correct me if I am wrong), what would be the threshold to decide whether to go for multiprocessing?\r\n\r\nPS: I am talking about CPython but please feel free to extend the answer to whatever you feel is necessary.', '6', '2019-11-19 10:02:19', '1');
INSERT INTO `question` VALUES ('70', 'Prebuilt sparc bare metal cross compiler not working', 'Downloaded a prebuilt cross compiler sparc-elf-4.2.2 and has set the PATH to sparc-elf-4.4.4/bin after which i ran sparc-elf-gcc -o matrixmul matrixmul.c on the terminal only to find the following response\r\n\r\n/home/root/sparc-elf-4.4.2/bin/sparc-elf-gcc: No such file or directory\r\nI have no idea as to why this response .', '11', '2019-11-19 10:02:23', '9');
INSERT INTO `question` VALUES ('71', 'Is it true that in multiprocessing, each process gets it\'s own GIL in CPython? How different is that from creating new runtimes?', 'Are there any caveats to it? I have a few questions related to it.\r\n\r\nHow costly is it to create more GILs? Is it any different from creating a separate python runtime? Once a new GIL is created, will it create everything (objects, variables, stack, heap) from scratch as required in that process or a copy of everything in the present heap and the stack is created? (Garbage collection would malfunction if they are working on same objects.) Are the pieces of code being executed also copied to new CPU cores? Also can i relate one GIL to one CPU core?\r\n\r\nNow copying things is a fairly CPU intensive task (correct me if I am wrong), what would be the threshold to decide whether to go for multiprocessing?\r\n\r\nPS: I am talking about CPython but please feel free to extend the answer to whatever you feel is necessary.', '4', '2019-11-19 10:02:27', '1');
INSERT INTO `question` VALUES ('72', 'How to read a large file line by line?', 'I want to read a file line by line, but without completely loading it in memory.\nMy file is too large to open in memory, and if try to do so I always get out of memory errors.The file size is 1 GB.', '1', '2020-03-02 19:56:06', '2');
